// Certification articles — one per badge on the site. Each is an honest story
// scaffold (bracketed [ ] spots are for Kranthi to personalize), a real
// learning path, verified resources, and verified exam facts. All external
// links were checked (HTTP 200) before publishing. Rendered by BlogPost's
// prose renderer (blocks: p / h / list / steps / resources / facts / note / quote).

const editNote = {
  type: 'note',
  text: 'Draft — anything in [brackets] is a spot to drop in your own specifics (dates, scores, the moment it clicked). Delete this note when you have made it yours.',
}

export const CERT_POSTS = [
  // ------------------------------------------- Claude Certified Associate
  {
    slug: 'claude-foundations',
    title: 'Claude Certified Associate — Foundations',
    subtitle: 'Being deliberate about a tool I already used every day',
    category: 'certs',
    date: '2026-08-07',
    readingMins: 5,
    excerpt: 'Anthropic\'s associate-level credential for using Claude well: choosing the right model, writing prompts that hold up, checking the output, and knowing where the limits are.',
    body: [
      editNote,
      { type: 'p', text: 'I had been using Claude daily long before I sat this exam — drafting, debugging, rubber-ducking through incidents. That is exactly why I wanted the credential. Using a tool constantly is not the same as using it deliberately, and I wanted to find the gaps between the two. [Add: the moment you realised you were prompting on autopilot.]' },
      { type: 'p', text: 'Anthropic frames this one at client-facing and delivery practitioners: people who apply Claude to real business work, judge whether the output is actually good, pick the right product and model for the job, and use it responsibly. That framing matched how I wanted to think about it.' },
      { type: 'facts', items: [
        { k: 'Issuer', v: 'Anthropic' },
        { k: 'Level', v: 'Associate' },
        { k: 'Format', v: 'Proctored exam' },
        { k: 'Earned', v: '6 Aug 2026' },
        { k: 'Valid for', v: '1 year' },
      ] },
      { type: 'note', text: 'No question count, time limit, or price listed above — I could not find those stated on an official Anthropic page, and I would rather leave a gap than publish a guess. Everything above comes from the credential itself.' },
      { type: 'h', text: 'What it actually certifies' },
      { type: 'p', text: 'These are the skill areas attached to the badge by Anthropic — not my summary of them:' },
      { type: 'list', items: [
        'Prompt engineering — getting a useful answer on purpose rather than by luck.',
        'Model selection — knowing which Claude model fits the task, and what you trade away.',
        'Output evaluation — checking and refining what comes back instead of shipping it raw.',
        'Claude Projects — giving work a persistent home with the right context loaded.',
        'Knowledge management — feeding Claude the right material, and knowing what not to.',
        'Workflow integration — putting it into real day-to-day work, not a side experiment.',
        'Responsible AI — privacy, limits, and where a human has to stay in the loop.',
        'Troubleshooting — recognising when the model is wrong and recovering.',
      ] },
      { type: 'h', text: 'The part that changed how I work' },
      { type: 'p', text: 'Output evaluation. It is easy to accept a confident answer because it is well written — and a well-written wrong answer is more dangerous than an obviously bad one. Prepping for this pushed me to verify before I trust, which is the same instinct good engineering already demands. [Add: a time Claude was confidently wrong and how you caught it.]' },
      { type: 'p', text: 'The second one was model selection. Reaching for the largest model every time is the equivalent of running every workload on the biggest instance available. Matching the model to the task is a real skill, and it is a cost and latency decision as much as a quality one.' },
      { type: 'h', text: 'The learning path I would repeat' },
      { type: 'steps', items: [
        { title: 'Use it seriously for real work first', text: 'This is not a cert you should cram for cold. The questions assume you have hit the friction yourself.' },
        { title: 'Work through Anthropic Academy', text: 'The official courses are free and map closely to how Anthropic expects the tools to be used.' },
        { title: 'Read the prompt engineering docs properly', text: 'Not skim — properly. Most of my own bad prompts were explained somewhere in there.' },
        { title: 'Learn the model line-up cold', text: 'Know what separates the models and when the trade-off is worth it.' },
        { title: 'Practise being the reviewer', text: 'Take answers Claude gave you and grade them. That habit is most of what the exam is testing.' },
      ] },
      { type: 'h', text: 'Was it worth it?' },
      { type: 'p', text: 'Yes — though not for the badge. It made me slower in a good way: more specific in what I ask for, more sceptical about what I get back, and clearer about the jobs I should not hand over at all. [Add your own verdict.]' },
      { type: 'h', text: 'Resources' },
      { type: 'resources', items: [
        { label: 'Anthropic Academy', sub: 'the official free courses', url: 'https://anthropic.skilljar.com/' },
        { label: 'Claude Certified Associate — Foundations', sub: 'official badge & criteria', url: 'https://www.credly.com/org/anthropic/badge/claude-certified-associate-foundations' },
        { label: 'Prompt engineering overview', sub: 'the docs worth reading twice', url: 'https://docs.claude.com/en/docs/build-with-claude/prompt-engineering/overview' },
        { label: 'Choosing a model', sub: 'the trade-offs, from the source', url: 'https://docs.claude.com/en/docs/about-claude/models/overview' },
        { label: 'Claude 101', sub: 'the fundamentals, plainly explained', url: 'https://support.anthropic.com/en/collections/4078531-claude-101' },
      ] },
      { type: 'resources', items: [
        { label: 'Verify my credential', sub: 'issued by Anthropic via Credly', url: 'https://www.credly.com/badges/e24a663a-082c-41b8-b7bf-c35e9900044a/public_url' },
      ] },
    ],
  },

  // ------------------------------------------------------------------ AWS SAA
  {
    slug: 'aws-saa',
    title: 'AWS Solutions Architect Associate',
    subtitle: 'How I learned to think in trade-offs, not services',
    category: 'certs',
    date: '2026-07-02',
    readingMins: 6,
    excerpt: 'The cert that turned a pile of AWS services into a way of designing systems. My story, the exact path I took, and the resources that actually moved the needle.',
    body: [
      editNote,
      { type: 'p', text: 'By the time I sat the Solutions Architect Associate, I had already been living inside AWS day to day [add: at Amazon, supporting Lambda / DynamoDB / API Gateway]. But there is a difference between fixing one service and being able to look at a blank diagram and design the whole thing. The SAA is where that shift happened for me.' },
      { type: 'p', text: 'It is the most popular AWS certification for a reason: it is broad enough to force you across compute, storage, networking, security, and cost — and deep enough that you stop memorising service names and start reasoning about trade-offs.' },
      { type: 'facts', items: [
        { k: 'Exam code', v: 'SAA-C03' },
        { k: 'Questions', v: '65' },
        { k: 'Duration', v: '130 min' },
        { k: 'Cost', v: '$150 USD' },
        { k: 'Passing score', v: '720 / 1000' },
        { k: 'Valid for', v: '3 years' },
      ] },
      { type: 'h', text: 'Why I went for it' },
      { type: 'p', text: '[Add your own why here.] For me it was partly proof and partly pressure: I wanted the architecture fundamentals to be muscle memory, not something I looked up mid-incident. [Add: what finally made you book the date.]' },
      { type: 'h', text: 'The four domains it tests' },
      { type: 'list', items: [
        'Design secure architectures (~30%) — IAM, encryption, network isolation.',
        'Design resilient architectures (~26%) — multi-AZ, decoupling, recovery.',
        'Design high-performing architectures (~24%) — the right compute/storage/db for the job.',
        'Design cost-optimized architectures (~20%) — because the cheapest design that meets the bar wins.',
      ] },
      { type: 'h', text: 'The learning path I would repeat' },
      { type: 'steps', items: [
        { title: 'Watch one deep video course end to end', text: 'Pick a single instructor and finish it. Do the hands-on labs in your own account — reading is not the same as building.' },
        { title: 'Read the official exam guide', text: 'It lists exactly what is in scope. Treat it as your checklist, not an afterthought.' },
        { title: 'Build one small thing per domain', text: 'A multi-AZ web app, an S3 static site with CloudFront, a Lambda + DynamoDB API. Small, real, yours.' },
        { title: 'Grind practice exams until patterns emerge', text: 'The exam rewards recognising scenarios. When you can explain why the other three answers are wrong, you are ready.' },
        { title: 'Review only your weak domains', text: 'In the last week, stop re-watching what you know. Attack the two domains with your lowest practice scores.' },
      ] },
      { type: 'h', text: 'Resources that actually helped' },
      { type: 'resources', items: [
        { label: 'Official AWS SAA certification page', sub: 'exam overview, straight from AWS', url: 'https://aws.amazon.com/certification/certified-solutions-architect-associate/' },
        { label: 'SAA-C03 official exam guide (PDF)', sub: 'the definitive scope checklist', url: 'https://d1.awsstatic.com/training-and-certification/docs-sa-assoc/AWS-Certified-Solutions-Architect-Associate_Exam-Guide.pdf' },
        { label: 'AWS Skill Builder', sub: 'official labs & practice question sets', url: 'https://skillbuilder.aws/' },
        { label: "Adrian Cantrill's SA Associate course", sub: 'deep, diagram-heavy, hands-on', url: 'https://learn.cantrill.io/' },
        { label: 'Tutorials Dojo practice exams', sub: 'the gold standard for exam-style questions', url: 'https://tutorialsdojo.com/' },
      ] },
      { type: 'h', text: "What I'd tell someone starting" },
      { type: 'list', items: [
        'Build in a real account. The free tier is enough for almost everything on the exam.',
        'When you get a practice question wrong, write one sentence on why. That notebook is your real study guide.',
        'Learn the trade-offs, not the trivia. The exam is scenario-based; the job is even more so.',
      ] },
      { type: 'quote', text: 'The SAA did not make me an architect. It gave me the vocabulary to become one.' },
      { type: 'resources', items: [
        { label: 'Verify my badge on Credly', sub: 'the real, issued credential', url: 'https://www.credly.com/badges/4528a7ce-198b-4edd-94dd-54bea26bcafd' },
      ] },
    ],
  },

  // ------------------------------------------------------- Couchbase Admin
  {
    slug: 'couchbase-admin',
    title: 'Couchbase Certified — Administrator',
    subtitle: 'Learning to keep a distributed database boringly reliable',
    category: 'certs',
    date: '2026-07-01',
    readingMins: 4,
    excerpt: 'Running Couchbase in support taught me the failure modes; the administrator cert made me formalise them. Buckets, XDCR, rebalances — and how I studied them.',
    body: [
      editNote,
      { type: 'p', text: 'I came to this one from the trenches [add: while at Couchbase, working distributed clusters day to day]. When you have already watched a rebalance stall or an XDCR stream lag in production, the administrator material stops being abstract — it is a checklist of things you have felt go wrong.' },
      { type: 'facts', items: [
        { k: 'Provider', v: 'Couchbase' },
        { k: 'Level', v: 'Associate' },
        { k: 'Format', v: 'Online, self-paced' },
        { k: 'Cost', v: 'Free' },
        { k: 'Focus', v: 'Cluster & data ops' },
      ] },
      { type: 'h', text: 'What it covers' },
      { type: 'list', items: [
        'Cluster setup, buckets, scopes and collections.',
        'Rebalancing, failover and node management.',
        'Cross Data Center Replication (XDCR) and disaster recovery.',
        'Monitoring, backups, and security basics.',
      ] },
      { type: 'h', text: 'The learning path' },
      { type: 'steps', items: [
        { title: 'Stand up a real cluster', text: 'A local multi-node cluster (or Capella free tier) teaches more in an hour than any slide deck.' },
        { title: 'Break it on purpose', text: 'Kill a node. Trigger a failover. Watch a rebalance. Understanding recovery is the whole job.' },
        { title: 'Work the official Couchbase learning tracks', text: 'They map closely to the exam and are free.' },
        { title: 'Practise the operational runbooks', text: 'Backups, restores, XDCR setup — until you can do them without notes.' },
      ] },
      { type: 'h', text: 'Resources' },
      { type: 'resources', items: [
        { label: 'Couchbase learning portal', sub: 'official courses, tracks & certification exams', url: 'https://learn.couchbase.com/' },
        { label: 'Verify my badge on Credly', sub: 'the issued credential', url: 'https://www.credly.com/badges/21986ffd-3145-4312-8ed8-8f870454b7d5/public_url' },
      ] },
      { type: 'p', text: '[Add a line here about the moment Couchbase internals actually clicked for you — mine was the first time I traced an XDCR lag back to its root cause.]' },
    ],
  },

  // ----------------------------------------------------- Couchbase Python
  {
    slug: 'couchbase-python',
    title: 'Couchbase Certified — Python Developer',
    subtitle: 'Talking to a document database the right way',
    category: 'certs',
    date: '2026-06-30',
    readingMins: 4,
    excerpt: 'The developer track: SDKs, N1QL/SQL++, and the mental model shift from rows and joins to documents and keys. How I picked it up.',
    body: [
      editNote,
      { type: 'p', text: 'Coming from a SQL background, the hardest part was not the Python SDK — it was unlearning the relational reflex. Couchbase rewards you for modelling around access patterns and keys, not normalised tables. This cert is where that clicked.' },
      { type: 'facts', items: [
        { k: 'Provider', v: 'Couchbase' },
        { k: 'Level', v: 'Associate' },
        { k: 'Track', v: 'Python SDK' },
        { k: 'Format', v: 'Online, self-paced' },
        { k: 'Cost', v: 'Free' },
      ] },
      { type: 'h', text: 'What it covers' },
      { type: 'list', items: [
        'Connecting and doing key-value CRUD with the Python SDK.',
        'Querying with N1QL / SQL++ (SQL for JSON documents).',
        'Document data modelling — embedding vs. referencing.',
        'Working with collections, and handling errors and durability.',
      ] },
      { type: 'h', text: 'The learning path' },
      { type: 'steps', items: [
        { title: 'Write a tiny CRUD app', text: 'Connect, insert, get, upsert, delete. Nothing fancy — just get the SDK under your fingers.' },
        { title: 'Learn SQL++ by rewriting SQL you know', text: 'Take queries you would write against Postgres and express them against JSON documents.' },
        { title: 'Model one domain two ways', text: 'Embed everything, then split into references. Feel the trade-offs in query complexity and update cost.' },
        { title: 'Do the official Python developer track', text: 'It maps to the exam and gives you the runnable examples.' },
      ] },
      { type: 'h', text: 'Resources' },
      { type: 'resources', items: [
        { label: 'Couchbase learning portal', sub: 'developer tracks & certification exams', url: 'https://learn.couchbase.com/' },
        { label: 'Verify my badge on Credly', sub: 'the issued credential', url: 'https://www.credly.com/badges/6351ce61-4f3f-460e-935c-5b0e89e39c65' },
      ] },
    ],
  },

  // --------------------------------------------------- Couchbase Architect
  {
    slug: 'couchbase-architect',
    title: 'Couchbase Certified — Architect',
    subtitle: 'From "it works" to "it works at scale, and survives a region loss"',
    category: 'certs',
    date: '2026-06-29',
    readingMins: 4,
    excerpt: 'The architect track pulls the admin and developer views together: sizing, services, replication topology, and designing for failure. My path through it.',
    body: [
      editNote,
      { type: 'p', text: 'If the administrator cert is about keeping one cluster healthy and the developer cert is about talking to it well, the architect cert is about the decisions you make before any of that: how to size it, where to place services, and what happens when a whole data centre disappears.' },
      { type: 'facts', items: [
        { k: 'Provider', v: 'Couchbase' },
        { k: 'Level', v: 'Associate' },
        { k: 'Focus', v: 'Solution architecture' },
        { k: 'Format', v: 'Online, self-paced' },
        { k: 'Cost', v: 'Free' },
      ] },
      { type: 'h', text: 'What it covers' },
      { type: 'list', items: [
        'Multi-Dimensional Scaling — placing Data, Index, Query, Search services deliberately.',
        'Cluster sizing and capacity planning for a workload.',
        'Replication and XDCR topologies for high availability and DR.',
        'Choosing the right access pattern: key-value vs. query vs. search vs. analytics.',
      ] },
      { type: 'h', text: 'The learning path' },
      { type: 'steps', items: [
        { title: 'Start from a workload, not a cluster', text: 'Read/write ratio, latency target, data size. Every architecture decision falls out of these.' },
        { title: 'Map services to nodes on paper', text: 'Practise separating Data / Index / Query so one hot service cannot starve another.' },
        { title: 'Design a two-region topology', text: 'Sketch active-active vs. active-passive XDCR and reason about failover and conflict handling.' },
        { title: 'Work the official architect track', text: 'It ties the admin and developer knowledge into design decisions.' },
      ] },
      { type: 'h', text: 'Resources' },
      { type: 'resources', items: [
        { label: 'Couchbase learning portal', sub: 'architect track & certification exams', url: 'https://learn.couchbase.com/' },
        { label: 'Verify my badge on Credly', sub: 'the issued credential', url: 'https://www.credly.com/badges/e87a7035-55d0-4612-b5b4-8dc031560433' },
      ] },
      { type: 'quote', text: 'Architecture is just naming your failure modes before they name themselves.' },
    ],
  },

  // ------------------------------------------------- GitHub Foundations
  {
    slug: 'github-foundations',
    title: 'GitHub Foundations',
    subtitle: 'Proving the fundamentals of the platform I work on every day',
    category: 'certs',
    date: '2026-07-05',
    readingMins: 4,
    excerpt: 'The entry point to the GitHub certification track — Git, repositories, collaboration, and the wider platform. Quick to prep if you use GitHub daily.',
    body: [
      editNote,
      { type: 'p', text: 'Working at GitHub on Actions, most of this is daily reality. But Foundations is worth doing precisely because it forces you to be precise about the basics — the difference between Git and GitHub, exactly what a fork is, how protected branches and permissions actually behave.' },
      { type: 'facts', items: [
        { k: 'Exam code', v: 'GH-900' },
        { k: 'Questions', v: '~75' },
        { k: 'Duration', v: '~100 min' },
        { k: 'Cost', v: '$99 USD' },
        { k: 'Passing score', v: '700 / 1000' },
        { k: 'Valid for', v: '2 years' },
      ] },
      { type: 'h', text: 'What it covers' },
      { type: 'list', items: [
        'Git and GitHub fundamentals — commits, branches, merges, forks.',
        'Working with repositories and managing files.',
        'Collaboration — issues, pull requests, reviews, discussions.',
        'Projects, and modern practices like GitHub Actions and Codespaces.',
        'Privacy, security, permissions, and the GitHub community.',
      ] },
      { type: 'h', text: 'The learning path' },
      { type: 'steps', items: [
        { title: 'Read the official study guide once', text: 'It is short and lists every objective. This is your map.' },
        { title: 'Do the Microsoft Learn GitHub modules', text: 'Free, hands-on, and aligned to the exam objectives.' },
        { title: 'Use GitHub for a real thing', text: 'Open issues, make PRs, review one, protect a branch. Muscle memory beats memorisation.' },
        { title: 'Take a couple of practice runs', text: 'Mostly to get used to the phrasing — the content is not the hard part if you use GitHub.' },
      ] },
      { type: 'h', text: 'Resources' },
      { type: 'resources', items: [
        { label: 'GitHub Foundations — Microsoft Learn', sub: 'official exam page', url: 'https://learn.microsoft.com/en-us/credentials/certifications/github-foundations/' },
        { label: 'GH-900 study guide', sub: 'the official objective checklist', url: 'https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/gh-900' },
        { label: 'GitHub certifications hub', sub: 'the full cert track & prep', url: 'https://resources.github.com/learn/certifications/' },
        { label: 'Register the exam', sub: 'GitHub exam registration', url: 'https://examregistration.github.com/' },
      ] },
      { type: 'resources', items: [
        { label: 'Verify my credential', sub: 'issued via Microsoft', url: 'https://learn.microsoft.com/en-us/users/KranthiAkkumahanthi-6332/credentials/D4C54954A4FE7D48' },
      ] },
    ],
  },

  // ------------------------------------------------ GitHub Administration
  {
    slug: 'github-administration',
    title: 'GitHub Administration',
    subtitle: 'Running GitHub at organisation and enterprise scale',
    category: 'certs',
    date: '2026-07-06',
    readingMins: 4,
    excerpt: 'The step up from Foundations: managing orgs, members, policies, security and integrations for a whole company. What it covers and how I prepared.',
    body: [
      editNote,
      { type: 'p', text: 'Foundations proves you can use GitHub; Administration proves you can run it for everyone else. Coming from a support role [add: on GitHub Actions], I saw the admin side constantly — the org policy that blocked a workflow, the SSO config, the permission model behind a "why can\'t I merge?" ticket. This cert made that knowledge deliberate.' },
      { type: 'facts', items: [
        { k: 'Provider', v: 'GitHub (via Microsoft)' },
        { k: 'Level', v: 'Advanced' },
        { k: 'Delivery', v: 'Proctored, online' },
        { k: 'Focus', v: 'Org & enterprise admin' },
      ] },
      { type: 'h', text: 'What it covers' },
      { type: 'list', items: [
        'Organisation and enterprise account management.',
        'Members, teams, roles, and the permission model.',
        'Authentication and security — SSO/SAML, 2FA policies.',
        'Policies, compliance, and audit logs.',
        'Integrations, apps, and automation at scale.',
      ] },
      { type: 'h', text: 'The learning path' },
      { type: 'steps', items: [
        { title: 'Create a free organisation and explore every settings page', text: 'The admin surface is huge; clicking through it is the fastest way to internalise it.' },
        { title: 'Work the Microsoft Learn GitHub admin modules', text: 'They walk the org/enterprise controls objective by objective.' },
        { title: 'Map real scenarios to settings', text: 'Onboarding a team, enforcing 2FA, restricting an app — practise the "how would I do this" reflex.' },
        { title: 'Register and book once the objectives feel familiar', text: 'Use the official exam registration below.' },
      ] },
      { type: 'h', text: 'Resources' },
      { type: 'resources', items: [
        { label: 'GitHub training on Microsoft Learn', sub: 'official modules for the admin track', url: 'https://learn.microsoft.com/en-us/training/github/' },
        { label: 'GitHub certifications hub', sub: 'the full cert track & prep', url: 'https://resources.github.com/learn/certifications/' },
        { label: 'Register the exam', sub: 'GitHub exam registration', url: 'https://examregistration.github.com/' },
      ] },
      { type: 'resources', items: [
        { label: 'Verify my credential', sub: 'issued via Microsoft', url: 'https://learn.microsoft.com/en-us/users/kranthiakkumahanthi-6332/credentials/34edb692ae79316e' },
      ] },
    ],
  },

  // ------------------------------------------------ GitHub Actions (GH-200)
  {
    slug: 'github-actions',
    title: 'GitHub Actions',
    subtitle: 'Certifying the thing I do all day',
    category: 'certs',
    date: '2026-07-04',
    readingMins: 5,
    excerpt: 'CI/CD, workflows, runners, reusable workflows and secrets — the exam on the platform I support for a living. What it covers and how I would prepare.',
    body: [
      editNote,
      { type: 'p', text: 'This is the one closest to my day job — I work on GitHub Actions, so the exam content is the same ground I walk with customers: workflow syntax that will not trigger, a reusable workflow passing the wrong secret, a self-hosted runner that will not come online. Sitting the cert was less about learning it cold and more about making the mental model airtight.' },
      { type: 'facts', items: [
        { k: 'Exam code', v: 'GH-200' },
        { k: 'Provider', v: 'GitHub (via Microsoft)' },
        { k: 'Delivery', v: 'Proctored, online' },
        { k: 'Focus', v: 'CI/CD with Actions' },
        { k: 'Level', v: 'Intermediate' },
      ] },
      { type: 'h', text: 'What it covers' },
      { type: 'list', items: [
        'Workflow authoring — triggers, jobs, steps, expressions and contexts.',
        'Actions — using marketplace actions and writing your own.',
        'Reusable workflows, composite actions, and matrix builds.',
        'Runners — GitHub-hosted vs. self-hosted, and runner groups.',
        'Secrets, variables, environments, and deployment protection rules.',
        'Security hardening — permissions, OIDC, and least privilege.',
      ] },
      { type: 'h', text: 'The learning path' },
      { type: 'steps', items: [
        { title: 'Automate something you actually have', text: 'Add CI to a real repo: lint, test, build on every push. The exam mirrors real usage.' },
        { title: 'Write a custom + a composite action', text: 'Once you have built one, inputs/outputs and composition stop being abstract.' },
        { title: 'Break into reusable workflows and matrices', text: 'Call one workflow from another; run a matrix across versions. Understand secret passing between them.' },
        { title: 'Stand up a self-hosted runner', text: 'Register one, run a job on it, then reason about runner groups and security.' },
        { title: 'Study environments, OIDC and permissions', text: 'The security domain is where most people lose points — deployment protection and least-privilege tokens.' },
      ] },
      { type: 'h', text: 'Resources' },
      { type: 'resources', items: [
        { label: 'GitHub Actions — Microsoft Learn', sub: 'official exam page', url: 'https://learn.microsoft.com/en-us/credentials/certifications/github-actions/' },
        { label: 'GH-200 study guide', sub: 'the official objective checklist', url: 'https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/gh-200' },
        { label: 'GitHub Actions documentation', sub: 'the source of truth — read it, do not skim it', url: 'https://docs.github.com/en/actions' },
        { label: 'Register the exam', sub: 'GitHub exam registration', url: 'https://examregistration.github.com/' },
      ] },
      { type: 'h', text: "What I'd tell someone starting" },
      { type: 'list', items: [
        'The docs are unusually good. Most exam answers are one careful read away.',
        'Know the difference between a reusable workflow and a composite action cold — it trips people up.',
        'Understand how secrets do (and do not) flow into called workflows and forks. It is both exam gold and real-world safety.',
      ] },
      { type: 'quote', text: 'Supporting Actions taught me every way a workflow can fail. The cert just made me say why, precisely.' },
      { type: 'resources', items: [
        { label: 'Verify my credential', sub: 'issued via Microsoft', url: 'https://learn.microsoft.com/en-us/users/KranthiAkkumahanthi-6332/credentials/AF357DA2107EC50B' },
      ] },
    ],
  },
  // ----------------------------------------------- GitHub Copilot (GH-300)
  {
    slug: 'github-copilot',
    title: 'GitHub Copilot',
    subtitle: 'Certifying the tool I write with every day',
    category: 'certs',
    date: '2026-08-20',
    readingMins: 5,
    excerpt: 'GH-300 — prompt engineering, context crafting, data handling, content exclusions and responsible use. The exam on the assistant that is now part of how I work.',
    body: [
      editNote,
      { type: 'p', text: 'Most of this list is about systems I support. This one is about how I work. Copilot is in my editor, my terminal and my pull requests, and the difference between it being useful and being noise comes down to the things this exam actually tests — how much context you give it, and how much you trust what comes back.' },
      { type: 'p', text: 'That made the exam an odd one to prepare for. The productivity domains were muscle memory. The ones I had to be deliberate about were the admin-side topics: what leaves your machine, what gets retained, and what content exclusions do and do not stop. [Add: the domain you found hardest.]' },
      { type: 'facts', items: [
        { k: 'Exam code', v: 'GH-300' },
        { k: 'Provider', v: 'GitHub (via Microsoft)' },
        { k: 'Delivery', v: 'Proctored, online' },
        { k: 'Duration', v: '100 minutes' },
        { k: 'Level', v: 'Intermediate' },
      ] },
      { type: 'h', text: 'What it covers' },
      { type: 'list', items: [
        'Using GitHub Copilot responsibly — where the human stays in the loop.',
        'Copilot features across the plans, and what each one is actually for.',
        'How Copilot handles data, and the architecture behind a suggestion.',
        'Prompt engineering and context crafting — the part that changes your day.',
        'Improving developer productivity without outsourcing your judgement.',
        'Privacy, content exclusions, and safeguards.',
      ] },
      { type: 'h', text: 'The learning path' },
      { type: 'steps', items: [
        { title: 'Use it on something real, then watch where it fails', text: 'The exam rewards knowing its limits. You only learn those on a codebase you understand well enough to catch a wrong answer.' },
        { title: 'Practise context, not prompts', text: 'Open files, selections and comments shape a suggestion far more than clever phrasing. Prove it to yourself: same ask, different files open.' },
        { title: 'Go past inline completion', text: 'Chat, slash commands, the CLI, code review, the coding agent. Knowing what each surface is for is straightforwardly examinable.' },
        { title: 'Read the data and privacy docs properly', text: 'Retention, exclusions and what a suggestion is built from. This is the domain most people skim and most people lose points on.' },
        { title: 'Set up content exclusions yourself', text: 'Configure them on a repo, then hit one. Seeing the tool refuse makes the policy concrete instead of abstract.' },
      ] },
      { type: 'h', text: 'Resources' },
      { type: 'resources', items: [
        { label: 'GitHub Copilot — Microsoft Learn', sub: 'official exam page', url: 'https://learn.microsoft.com/en-us/credentials/certifications/github-copilot/' },
        { label: 'GH-300 study guide', sub: 'the official objective checklist', url: 'https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/gh-300' },
        { label: 'Practice assessment', sub: 'free, and a fair read on your readiness', url: 'https://learn.microsoft.com/en-us/credentials/certifications/github-copilot/practice/assessment?assessment-type=practice&assessmentId=218035372&practice-assessment-type=certification' },
        { label: 'Exam sandbox', sub: 'the real interface, before exam day', url: 'https://ghcertdemo.starttest.com' },
        { label: 'GitHub Copilot documentation', sub: 'the source of truth for the policy domains', url: 'https://docs.github.com/en/copilot' },
        { label: 'Register the exam', sub: 'GitHub exam registration', url: 'https://examregistration.github.com/' },
      ] },
      { type: 'h', text: "What I'd tell someone starting" },
      { type: 'list', items: [
        'Daily use gets you the productivity domains and none of the governance ones. Budget your study time accordingly.',
        'Know the plan differences — a lot of "can Copilot do X?" questions are really "on which plan?".',
        'Content exclusions are a guardrail, not a guarantee. Understand precisely what they cover.',
        'Take the practice assessment early, not as a last check. It tells you which half you already know.',
      ] },
      { type: 'quote', text: 'The certification did not teach me to use Copilot. It made me able to say exactly when not to.' },
      { type: 'resources', items: [
        { label: 'Verify my credential', sub: 'issued via Microsoft', url: 'https://learn.microsoft.com/en-us/users/KranthiAkkumahanthi-6332/credentials/C753C701068CFDAA' },
      ] },
    ],
  },
]
